services:
  activity-bot:
    build: .
    volumes:
      - .:/app
      - ${DATA_PATH:-./data}:/data
    environment:
      - SPREADSHEET_ID=${SPREADSHEET_ID}
      - FRIEND_SHEET_NAME=${FRIEND_SHEET_NAME}
      - MY_SHEET_NAME=${MY_SHEET_NAME}
      - FRIEND_TELEGRAM_ID=${FRIEND_TELEGRAM_ID}
      - MY_TELEGRAM_ID=${MY_TELEGRAM_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_API_KEY=${TELEGRAM_BOT_API_KEY}
      - GOOGLE_CREDENTIALS=${GOOGLE_CREDENTIALS}
      - DATABASE_URL=/data/db/higher-pleasures.db
      - LOG_DIR=/data/logs
    restart: unless-stopped
    init: true
    user: "1000:1000"
  db_api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ${DATA_PATH:-./data}:/data
    environment:
      - DATABASE_URL=/data/db/higher-pleasures.db
    command: uvicorn src.db_api.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - activity-bot
    init: true
    user: "1000:1000"

volumes:
  activity_data:
    name: activity_bot_data