services:
  activity-bot:
    build: .
    volumes:
      - .:/app
      - /data/sqlite:/data/sqlite:rw
    environment:
      - SPREADSHEET_ID=${SPREADSHEET_ID}
      - FRIEND_SHEET_NAME=${FRIEND_SHEET_NAME}
      - MY_SHEET_NAME=${MY_SHEET_NAME}
      - FRIEND_TELEGRAM_ID=${FRIEND_TELEGRAM_ID}
      - MY_TELEGRAM_ID=${MY_TELEGRAM_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_API_KEY=${TELEGRAM_BOT_API_KEY}
      - GOOGLE_CREDENTIALS=${GOOGLE_CREDENTIALS}
      # Updated database URL to match volume mount point
      - DATABASE_URL=/data/sqlite/higher-pleasures.db
    restart: unless-stopped
    init: true
    user: "1000:1000"

volumes:
  activity_data:
    name: activity_bot_data  