[tool.ruff]
# Enable isort rules
lint.select = ["I"] 

[tool.ruff.lint.isort]
force-single-line = false
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
combine-as-imports = true
relative-imports-order = "closest-to-furthest"